version: '3.3'
services:
  zoo1:
    container_name: zoo-udl
    image: docker.io/zookeeper:3.8
    restart: unless-stopped
    ports:
      - "2181:2181"
    environment:
      - ZOO_4LW_COMMANDS_WHITELIST=mntr,conf,ruok
    volumes:
      - zookeeper1_data:/data
      - zookeeper1_datalog:/datalog
  solr1:
    image: docker.io/solr:9
    container_name: solr-udl
    restart: unless-stopped
    ports:
      - "8983:8983"
    depends_on:
      - zoo1
    environment:
      SOLR_HEAP: 2g
      ZK_HOST: zoo-udl:2181
    command: -c
    volumes:
      - solr1_data:/var/solr
#  clamd:
#    image: docker.io/clamav/clamav:stable
#    restart: unless-stopped
#    volumes:
#      - clam_data:/var/lib/clamav
#      - roda_data:/roda/data/
  siegfried1:
    image: ghcr.io/keeps/siegfried:v1.10.0
    restart: unless-stopped
    container_name: siegfried-udl
    environment:
      SIEGFRIED_HOST: 0.0.0.0
      SIEGFRIED_PORT: 5138
    volumes:
      - siegfried1_data:/root/siegfried/
      - roda1_data:/roda/data/
#        #swagger:
#        #image: docker.io/swaggerapi/swagger-ui:latest
        #restart: on-failure
        #ports:
        #- "8081:8080"
        #environment:
        #- URL=http://192.168.45.136:8080/api/openapi.json
        #- DOC_EXPANSION=none
        #- VALIDATOR_URL=none
  roda1:
    image: ghcr.io/nageru/roda:5.2.0-SNAPSHOT
    restart: unless-stopped
    container_name: roda-udl
    ports:
      - "8080:8080"
      - "8009:8009"
    depends_on:
      - solr1
      - siegfried1
    volumes:
      - roda1_data:/roda/data/
    environment:
       # Solr Cloud configuration
      - RODA_CORE_SOLR_TYPE=CLOUD
      - RODA_CORE_SOLR_CLOUD_URLS=zoo1:2181
      - SOLR_NUM_SHARDS=4
      - SOLR_REPLICATION_FACTOR=1
      ## Base plugin services configuration
      - SIEGFRIED_SERVER_URL=http://siegfried1:5138
      - CLAMD_TCPADDR=clamd
      - CLAMD_TCPSOCKET=3310
volumes:
  zookeeper1_data:
  zookeeper1_datalog:
  solr1_data:
  clam_data:
  siegfried1_data:
  roda1_data:
