version: '3.3'
services:
  zoo2:
    container_name: zoo2
    image: docker.io/zookeeper:3.8
    restart: unless-stopped
    ports:
      - "2182:2181"
    environment:
      - ZOO_4LW_COMMANDS_WHITELIST=mntr,conf,ruok
    volumes:
      - zookeeper2_data:/data
      - zookeeper2_datalog:/datalog
  solr2:
    container_name: solr2
    image: docker.io/solr:9
    restart: unless-stopped
    ports:
      - "8984:8983"
    depends_on:
      - zoo2
    environment:
      SOLR_HEAP: 2g
      ZK_HOST: zoo2:2181
    command: -c
    volumes:
      - solr2_data:/var/solr
  roda2:
    image: ghcr.io/nageru/roda:5.1.0-SNAPSHOT
    container_name: roda2
    restart: unless-stopped
    ports:
      - "8082:8080"
    depends_on:
      - solr2
      - siegfried2
    volumes:
      - roda2_data:/roda/data/
    environment:
      # Solr Cloud configuration
      - RODA_CORE_SOLR_TYPE=CLOUD
      - RODA_CORE_SOLR_CLOUD_URLS=zoo2:2181
      - SOLR_NUM_SHARDS=4
      - SOLR_REPLICATION_FACTOR=1
      # Base plugin services configuration
      - SIEGFRIED_SERVER_URL=http://siegfried2:5138
      - CLAMD_TCPADDR=clamd
      - CLAMD_TCPSOCKET=3310
  siegfried2:
    image: ghcr.io/keeps/siegfried:v1.10.0
    restart: unless-stopped
    container_name: siegfried2
    environment:
      SIEGFRIED_HOST: 0.0.0.0
      SIEGFRIED_PORT: 5138
    volumes:
      - siegfried2_data:/root/siegfried/
      - roda2_data:/roda/data/
volumes:
  zookeeper2_data:
  zookeeper2_datalog:
  solr2_data:
  roda2_data:
  siegfried2_data:
